# 1. Importing libraries and loading df

First things first I imported the basic libraries i wanted to work with. Pandas is responsible for data wrangling and manipulation while numpy is for data analysis and array manipulations, quite handy for large datasets. Eventually, I did not utilize this library in this project.

In [447]:
import pandas as pd
import numpy as np

Next step is to assign the dataset to a variable. First I created the variable prime and copied this to df. This lets me compare the start and the end result.

In [448]:
primary = pd.read_csv("data/messy_IMDB_dataset.csv", encoding="cp1252", delimiter=";")
df = primary.copy()
df.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

In [449]:
df.dtypes

IMBD title ID         str
Original titlÊ        str
Release year          str
Genrë¨                str
Duration              str
Country               str
Content Rating        str
Director              str
Unnamed: 8        float64
Income                str
 Votes                str
Score                 str
dtype: object

# 2. Cleaning

### Column names
Since column names contain typos and spaces, this is the first obstacle I solved. I renamed the columns in a way that lets me query them easily. (Using dashes)

In [450]:
df = df.rename(columns={"IMBD title ID": "Title",
                        "Original titlÊ" : "Original_title",
                        "Release year": "Release_year",
                        "Genrë¨" : "Genre",
                        "Content Rating": "Content_rating",
                        })

In [451]:
df.columns

Index(['Title', 'Original_title', 'Release_year', 'Genre', 'Duration',
       'Country', 'Content_rating', 'Director', 'Unnamed: 8', 'Income',
       ' Votes ', 'Score'],
      dtype='str')

### Removing noise in columns
One column did not have any significant meaning, so I removed it from the dataframe.

In [452]:
df = df.drop(columns=["Unnamed: 8"])
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
96,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
97,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
99,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

### Overviewing data integrity

#### I. Title

- Every record in column "Title" mathces the pattern of 2 letters followed by 7 digits.
- Only one exception, this record contains NaN in every column, so I dropped it later.

In [453]:
# Title
df[df["Title"].str.contains(r"[a-z]{2}\d{7}")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
96,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
97,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
99,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

To further narrow the pattern, I also noticed that the title always starts with tt. No other words combination were visible.

In [454]:
# Every row in title starts with tt then 7 digits
df[df["Title"].str.contains(r"tt\d{7}")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
96,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
97,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
99,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

Here I dropped the row that does not contain any information.

In [455]:
df[~df["Title"].str.contains(r"[a-z]{2}\d{7}")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [456]:
df = df.drop(index=13).reset_index(drop=True)
len(df)

100

#### II. Release year
Since release year had multiple formats, I united them into a simple one. Most of the dates followed the yyyy-mm-dd format so I chose this as my basis. Then I extraced from every row the year, month and day and formulated into yyyy-mm-dd.

In [457]:
# Most of the date has the format yyyy-mm-dd, so extract them and then reunite later
df[df["Release_year"].str.contains(r"\d{4}-\d{2}-\d{2}")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
6,tt0108052,Schindler's List,1994-03-11,"Biography, Drama, History",Nan,USA,R,Steven Spielberg,$ 322287794,1.183.248,8.9
7,tt0050083,12 Angry Men,1957-09-04,"Crime, Drama",96,USA,Not Rated,Sidney Lumet,$ 576,668.473,8.9
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
96,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

In [458]:
# These does not follow the format, 9 cases
# since almost all of them are different the easieast is to alter them manually
df[~df["Release_year"].str.contains(r"\d{4}-\d{2}-\d{2}")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
5,tt0167260,The Lord of the Rings: The Return of the King,22 Feb 04,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,$ 1142271098,1.604.280,08.9
9,tt0137523,Fight Club,10-29-99,Drama,Inf,UK,R,David Fincher,$ 101218804,1.807.440,8.8
12,tt0060196,"Il buono, il brutto, il cattivo",23rd December of 1966,Western,161,Italy,Approved,Sergio Leone,$ 25252481,672.499,8.8
14,tt0167261,The Lord of the Rings: The Two Towers,01/16-03,"Action, Adventure, Drama",179,New Zeland,PG-13,Peter Jackson,$ 951227416,1.449.778,8.7.
17,tt0073486,One Flew Over the Cuckoo's Nest,18/11/1976,Drama,-,USA,R,Milos Forman,$ 108997629,891.071,8.7
44,tt0034583,Casablanca,21-11-46,"Drama, Romance, War",102,USA,PG,Michael Curtiz,$ 4374761,509.953,8.3
69,tt0043014,Sunset Blvd.,"The 6th of marzo, year 1951","Drama, Film-Noir",110,USA,NaN,Billy Wilder,$ 299645,195.789,8.0

In [459]:
df.iloc[1,2] = "1972-09-21"
df.iloc[2,2] = "2008-07-23"
df.iloc[5,2] = "2022-02-04"
df.iloc[9,2] = "1999-10-29"
df.iloc[12,2] = "1966-12-23"
df.iloc[14,2] = "2003-01-16"
df.iloc[17,2] = "1976-11-18"
df.iloc[44,2] = "1946-11-21"
df.iloc[69,2] = "1951-03-06"
df[~df["Release_year"].str.contains(r"\d{4}-\d{2}-\d{2}")]
# everything follows the rule above, now change the data type to date

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income,  Votes , Score]
Index: []

In [460]:
df["Release_year"] = df["Release_year"].str.replace("-", ".")
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

#### III. Moving on to genre

In [461]:
# It follows the rule that only contain upper, lower case letters and comma
df[~df["Genre"].str.contains(r"[a-z|,|A-Z]+")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income,  Votes , Score]
Index: []

In [462]:
# made sure the rule is strict, it contains only letters.
df[df["Genre"].str.contains(r"\d")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income,  Votes , Score]
Index: []

#### IV. Duration

First I checked the records that contain something else other than digits

In [463]:
df[df["Duration"].str.contains(r"\D")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
6,tt0108052,Schindler's List,1994.03.11,"Biography, Drama, History",Nan,USA,R,Steven Spielberg,$ 322287794,1.183.248,8.9
9,tt0137523,Fight Club,1999.10.29,Drama,Inf,UK,R,David Fincher,$ 101218804,1.807.440,8.8
11,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2002.01.18,"Action, Adventure, Drama",178c,New Zesland,PG-13,Peter Jackson,$ 887934303,1.619.920,8.8
15,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.09.19,"Action, Adventure, Fantasy",Not Applicable,USA,PG,Irvin Kershner,$ 549265501,1.132.073,"8,7e-0"
17,tt0073486,One Flew Over the Cuckoo's Nest,1976.11.18,Drama,-,USA,R,Milos Forman,$ 108997629,891.071,8.7

Then I extracted the digits from the column and dropped the letters or dashes, dots etc.

In [464]:
df["Duration"] = df["Duration"].str.extract(r"(\d+)")
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

After this the column is united. In this column every record contains only digits.

In [465]:
df[df["Duration"].str.contains(r"\D")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income,  Votes , Score]
Index: []

Records that contain NaN should display the "No duration" class, however since it is a numerical column, adding this leads to future errors during the data analysis phase. The best way is to just leave them as NaN.

#### V. Country

First I checked the list and the counts of each country, and immidietly noticed that there are typos, generatig more classes. So regarding this column, I united the countries. USA and US. are the same. And did this with the rest of the countries

In [466]:
df["Country"].value_counts()

Country
USA             62
UK              12
Italy            4
Japan            4
France           3
South Korea      2
Germany          2
US               1
New Zealand      1
New Zesland      1
New Zeland       1
US.              1
Brazil           1
Italy1           1
India            1
Denmark          1
West Germany     1
Iran             1
Name: count, dtype: int64

- Here I replaced everything with USA that starts with US and ends some other way than A.
- Formulated logic for the rest of the countries as well.

In [467]:
df["Country"] = df["Country"].str.replace(r"^US\S?", "USA", regex=True) 
df["Country"] = df["Country"].str.replace(r"^(N|n)(w|W|ew) ?[z|Z]\w+|\w?[d|D]$", "New Zealand", regex=True)
df["Country"] = df["Country"].str.replace(r"\w?[i|I][taly]*[y|Y|t|T]\w?", "Italy", regex=True)

And resulted in an united list

In [468]:
df["Country"].value_counts()

Country
USA             64
UK              12
Italy            5
Japan            4
New Zealand      3
France           3
South Korea      2
Germany          2
Brazil           1
India            1
Denmark          1
West Germany     1
Iran             1
Name: count, dtype: int64

#### VI. Content rating

First listed the classes

In [469]:
df["Content_rating"].value_counts()

Content_rating
R            45
PG-13        12
PG           11
G             6
Not Rated     1
Approved      1
Unrated       1
Name: count, dtype: int64

In [470]:
#get indexes since its easier
not_rated_mask = ~df["Content_rating"].str.contains(r"^R|^PG-13|^PG|^G", na=False)

# replace those that does not follow the MPAA age restrictions with not rated.
df[~df["Content_rating"].str.contains(r"^R|^PG-13|^PG|^G")]

# the following list shows the records where content rating does not follow R, PG-13, PR or G rating

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
7,tt0050083,12 Angry Men,1957.09.04,"Crime, Drama",96,USA,Not Rated,Sidney Lumet,$ 576,668.473,8.9
12,tt0060196,"Il buono, il brutto, il cattivo",1966.12.23,Western,161,Italy,Approved,Sergio Leone,$ 25252481,672.499,8.8
26,tt0118799,La vita B9 bella,1997.12.20,"Comedy, Drama, Romance",116,Italy,NaN,Roberto Benigni,$ 230098753,605.648,8.6
27,tt6751668,Gisaengchung,2019.11.07,"Comedy, Drama, Thriller",132,South Korea,NaN,Bong Joon Ho,$ 257604912,470.931,8.6
29,tt0047478,Shichinin no samurai,1955.08.19,"Action, Adventure, Drama",207,Japan,Unrated,Akira Kurosawa,$ 322773,307.958,8.6
35,tt0110413,LÃ©on,1995.04.07,"Action, Crime, Drama",110,France,NaN,Luc Besson,$ 19552639,1.007.598,8.5
39,tt7286456,Joker,2019.10.03,"Crime, Drama, Thriller",122,USA,NaN,Todd Phillips,$ 1074251311,855.097,8.4
40,tt1675434,Intouchables,2012.02.24,"Biography, Comedy, Drama",112,France,NaN,"Olivier Nakache, Ã‰ric Toledano",$ 426588510,736.691,8.4
46,tt0095327,Hotaru no haka,2015.10.11,"Animation, Drama, War",89,Japan,NaN,Isao Takahata,$ 516962,225.438,8.3
47,tt0095765,Nuovo Cinema Paradiso,1988.11.17,Drama,155,Italy,NaN,Giuseppe Tornatore,$ 13826605,223.050,8.3
55,tt4154756,Avengers: Infinity War,2018.04.25,"Action, Adventure, Sci-Fi",149,USA,NaN,"Anthony Russo, Joe Russo",$ 2048359754,796.486,8.2
57,tt4154796,Avengers: Endgame,2019.04.24,"Action, Adventure, Drama",181,USA,NaN,"Anthony Russo, Joe Russo",$ 2797800564,754.786,8.2
61,tt0047396,Rear Window,1955.04.14,"Mystery, Thriller",112,USA,NaN,Alfred Hitchcock,$ 37032034,432.390,8.1
62,tt2380307,Coco,2017.12.28,"Animation, Adventure, Family",105,USA,NaN,"Lee Unkrich, Adrian Molina",$ 807083670,352.455,8.1
64,tt4633694,Spider-Man: Into the Spider-Verse,2018.12.25,"Animation, Action, Adventure",117,USA,NaN,"Bob Persichetti, Peter Ramsey",$ 375540831,335.892,8.1
65,tt1187043,3 Idiots,2009.12.25,"Comedy, Drama",170,India,NaN,Rajkumar Hirani,$ 60262836,332.217,8.1
68,tt0032553,The Great Dictator,1945.06.25,"Comedy, Drama, War",125,USA,NaN,Charles Chaplin,$ 969879,197.381,8.0
69,tt0043014,Sunset Blvd.,1951.03.06,"Drama, Film-Noir",110,USA,NaN,Billy Wilder,$ 299645,195.789,8.0
80,tt0066921,A Clockwork Orange,1972.09.07,"Crime, Drama, Sci-Fi",136,UK,NaN,Stanley Kubrick,$ 26903440,740.301,7.8
85,tt0093058,Full Metal Jacket,1987.10.09,"Drama, War",116,UK,NaN,Stanley Kubrick,$ 46357676,658.175,7.7
88,tt0033467,Citizen Kane,1948.11.25,"Drama, Mystery",119,USA,NaN,Orson Welles,$ 1594107,389.322,7.6
89,tt8579674,1917,2020.01.23,"Drama, War",119,USA,NaN,Sam Mendes,$ 384857224,362.897,7.6
91,tt0052357,Vertigo,1958.11.18,"Mystery, Romance, Thriller",128,USA,NaN,Alfred Hitchcock,$ 7796389,352.786,7.5
92,tt0053125,North by Northwest,1959.10.28,"Adventure, Mystery, Thriller",136,USA,NaN,Alfred Hitchcock,$ 73446,291.628,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

In [471]:
# Replace these records with "not rated" to unite them into a single group
df.loc[not_rated_mask, "Content_rating"] = "Not rated"

In [472]:
df["Content_rating"].value_counts()

Content_rating
R            45
Not rated    26
PG-13        12
PG           11
G             6
Name: count, dtype: int64

#### VII. Income

In [473]:
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,$ 15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,$ 1864182,213.152,7.4

In [474]:
# records that contains letters
df[df["Income"].str.contains(r"[a-zA-Z]")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"

Since there is only one case where letter is included it is easier to just manually replace it, than writing a sorting algorithm

In [475]:
# replace o with 0
df["Income"] = df["Income"].str.replace("o", "0")

In [476]:
# every row contains the $? -> yes
df[df["Income"].str.contains(r"\$")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 408,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,$ 15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,$ 1864182,213.152,7.4

In [477]:
# remove dollar and white space
df["Income"] = df["Income"].str.replace(r"\$", "", regex=True)
df["Income"] = df["Income"].str.replace(r"\s", "", regex=True)

In [478]:
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"408,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,1864182,213.152,7.4

In [479]:
# does the record only contain numbers or other characters like comma or dot aswell?
# well, there is one row that does not follow this rule, it contains commas
df[~df["Income"].str.contains(r"^[0-9]+$")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"408,035,783",1.098.714,"9,.0"

In [480]:
# just remove the commas so the records follow a single rule
df["Income"] = df["Income"].str.replace(",", "")
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,408035783,1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,1864182,213.152,7.4

Add dots every 3 digits to read number off easily.

In [481]:
# make sure records are numeric and not text
df["Income"] = pd.to_numeric(df["Income"], errors='coerce')
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,408035783,1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,1864182,213.152,7.4

#### VIII. Votes

In [482]:
# votes column had an invisible " " white space
df.columns = df.columns.str.strip()

In [483]:
# every number contains the dot as separator, lets remove it
df[~df["Votes"].str.contains(r"\.")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income, Votes, Score]
Index: []

In [484]:
df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,408035783,1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,1864182,213.152,7.4

#### IX. Score

First I looked at records that does not only contain digits.

In [485]:
df[~df["Score"].str.contains(r"^\d\.\d$")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,408035783,1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,"8,9f"
5,tt0167260,The Lord of the Rings: The Return of the King,2022.02.04,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,1142271098,1.604.280,08.9
8,tt1375666,Inception,2010.09.24,"Action, Adventure, Sci-Fi",148,USA,PG-13,Christopher Nolan,869784991,2.002.816,8..8
10,tt0109830,Forrest Gump,1994.10.06,"Drama, Romance",142,USA,PG-13,Robert Zemeckis,678229452,1.755.490,8:8
13,tt0133093,The Matrix,1999.05.07,"Action, Sci-Fi",NaN,USA,R,"Lana Wachowski, Lilly Wachowski",465718588,1.632.315,++8.7
14,tt0167261,The Lord of the Rings: The Two Towers,2003.01.16,"Action, Adventure, Drama",179,New Zealand,PG-13,Peter Jackson,951227416,1.449.778,8.7.
15,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.09.19,"Action, Adventure, Fantasy",NaN,USA,PG,Irvin Kershner,549265501,1.132.073,"8,7e-0"
20,tt0102926,The Silence of the Lambs,1991.03.05,"Crime, Drama, Thriller",118,USA,R,Jonathan Demme,272753884,1.234.134,"8,6"

In [486]:
# replace these, that do not follow the d.d rule
df["Score"] = df["Score"].str.replace(",.", ".")
df["Score"] = df["Score"].str.replace(r"\[a-zA-Z]", "", regex=True)
df["Score"] = df["Score"].str.replace(",", ".")
df["Score"] = df["Score"].str.replace("..", ".")
df["Score"] = df["Score"].str.replace(":", ".")
df["Score"] = df["Score"].str.replace(r"^9\.$", "9.0", regex=True)
df["Score"] = df["Score"].str.replace("++", "")

In [487]:
# do not write new rules, just extract the d.d values
df[~df["Score"].str.contains(r"^\d\.\d$")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,8.9f
5,tt0167260,The Lord of the Rings: The Return of the King,2022.02.04,"Action, Adventure, Drama",201,New Zealand,PG-13,Peter Jackson,1142271098,1.604.280,08.9
14,tt0167261,The Lord of the Rings: The Two Towers,2003.01.16,"Action, Adventure, Drama",179,New Zealand,PG-13,Peter Jackson,951227416,1.449.778,8.7.
15,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980.09.19,"Action, Adventure, Fantasy",NaN,USA,PG,Irvin Kershner,549265501,1.132.073,8.7e-0

In [488]:
df["Score"] = df["Score"].str.extract(r"(\d\.\d)")

In [489]:
# done
df[~df["Score"].str.contains(r"^\d\.\d$")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income, Votes, Score]
Index: []

#### X. Original title

In [490]:
# every title follows the rule: letters and numbers only
df[~df["Original_title"].str.contains(r"\w+")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income, Votes, Score]
Index: []

In [491]:
# these values contain white space, need to strip the entries
df[df["Original_title"].str.contains(r"\s+")]

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995.02.10,Drama,142,USA,R,Frank Darabont,28815245,2.278.845,9.3
1,tt0068646,The Godfather,1972.09.21,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,2008.07.23,"Action, Crime, Drama",152,USA,PG-13,Christopher Nolan,1005455211,2.241.615,9.0
3,tt0071562,The Godfather: Part II,1975.09.25,"Crime, Drama",220,USA,R,Francis Ford Coppola,408035783,1.098.714,9.0
4,tt0110912,Pulp Fiction,1994.10.28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1.780.147,8.9
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974.03.21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,156000000,236.285,7.5
96,tt0082096,Das Boot,1982.03.18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,11487676,226.427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965.12.20,Western,132,Italy,Not rated,Sergio Leone,15000000,226.039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011.10.21,Drama,123,Iran,PG-13,Asghar Farhadi,22926076,214.165,7.4
99,tt0045152,Singin' in the Rain,1953.02.05,"Comedy, Musical, Romance",103,USA,Not rated,Stanley Donen,1864182,213.152,7.4

In [492]:
# start and ends with white space, none so this is done
df[df["Original_title"].str.contains(r"(^\s\w+\s$)|(^\s\w+)|(\w+\s$)", regex=True)]

/var/folders/ft/mkxn4qpd7vdgfr1gm4t14r8h0000gn/T/ipykernel_40842/2011931043.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df["Original_title"].str.contains(r"(^\s\w+\s$)|(^\s\w+)|(\w+\s$)", regex=True)]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income, Votes, Score]
Index: []

#### XI. Director

In [493]:
# every director name follows that it only contains letters
df[~df["Director"].str.contains(r"[a-zA-Z]")]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income, Votes, Score]
Index: []

In [494]:
# now look at the free spaces
# sweet, no unwanted free space
df[df["Director"].str.contains(r"(^\s\w+\s$)|(^\s\w+)|(\w+\s$)", regex=True)]

/var/folders/ft/mkxn4qpd7vdgfr1gm4t14r8h0000gn/T/ipykernel_40842/3736945003.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df["Director"].str.contains(r"(^\s\w+\s$)|(^\s\w+)|(\w+\s$)", regex=True)]

Empty DataFrame
Columns: [Title, Original_title, Release_year, Genre, Duration, Country, Content_rating, Director, Income, Votes, Score]
Index: []

# 3. Final polishing

Adding $ to income column so numbers have meaning.

In [495]:
df = df.rename(columns={"Income": "Income_$"})

Then I converted every column into the appropriate data type.

In [496]:
# converting into numbers
df["Income_$"] = pd.to_numeric(df["Income_$"], errors='coerce')
df["Duration"] = pd.to_numeric(df["Duration"], errors='coerce')
df["Votes"] = df["Votes"].str.replace(".", "")
df["Votes"] = pd.to_numeric(df["Votes"], errors='coerce')
df["Score"] = pd.to_numeric(df["Score"], errors='coerce')

# converting into date
df["Release_year"] = pd.to_datetime(df["Release_year"], errors='coerce')

df

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income_$,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142.0,USA,R,Frank Darabont,28815245,2278845,9.3
1,tt0068646,The Godfather,1972-09-21,"Crime, Drama",175.0,USA,R,Francis Ford Coppola,246120974,1572674,9.2
2,tt0468569,The Dark Knight,2008-07-23,"Action, Crime, Drama",152.0,USA,PG-13,Christopher Nolan,1005455211,2241615,9.0
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220.0,USA,R,Francis Ford Coppola,408035783,1098714,9.0
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1780147,8.9
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129.0,USA,PG,George Roy Hill,156000000,236285,7.5
96,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149.0,West Germany,R,Wolfgang Petersen,11487676,226427,7.5
97,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132.0,Italy,Not rated,Sergio Leone,15000000,226039,7.4
98,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123.0,Iran,PG-13,Asghar Farhadi,22926076,214165,7.4
99,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103.0,USA,Not rated,Stanley Donen,1864182,213152,7.4

And created the final, cleaned dataframe.

In [497]:
final_df = df.copy()

----

# 4. Before vs. After

### Overall look before vs. after

In [498]:
primary.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

In [499]:
final_df.head()

,Title,Original_title,Release_year,Genre,Duration,Country,Content_rating,Director,Income_$,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142.0,USA,R,Frank Darabont,28815245,2278845,9.3
1,tt0068646,The Godfather,1972-09-21,"Crime, Drama",175.0,USA,R,Francis Ford Coppola,246120974,1572674,9.2
2,tt0468569,The Dark Knight,2008-07-23,"Action, Crime, Drama",152.0,USA,PG-13,Christopher Nolan,1005455211,2241615,9.0
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220.0,USA,R,Francis Ford Coppola,408035783,1098714,9.0
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",NaN,USA,R,Quentin Tarantino,222831817,1780147,8.9

### Datatypes before vs. after

In [502]:
primary.dtypes

IMBD title ID         str
Original titlÊ        str
Release year          str
Genrë¨                str
Duration              str
Country               str
Content Rating        str
Director              str
Unnamed: 8        float64
Income                str
 Votes                str
Score                 str
dtype: object

In [501]:
final_df.dtypes

Title                        str
Original_title               str
Release_year      datetime64[us]
Genre                        str
Duration                 float64
Country                      str
Content_rating               str
Director                     str
Income_$                   int64
Votes                      int64
Score                    float64
dtype: object

Saved the cleaned dataframe to a csv file.

In [500]:
final_df.to_csv("imdb_cleaned_data.csv", index=False)